title: Datum en tijd gebruiken
hero_image: images/banner.png
description: Datum en tijd gebruiken in JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2024-04-05"
steps:
  - 
    title: Datum en tijd gebruiken in JavaScript
