title: Using date and time
hero_image: images/banner.png
description: Using date and time in JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Using date and time in JavaScript
